In [12]:
#!pip install numpy

In [5]:
import numpy as np

In [14]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [24]:
a=[1,2,4,4,'ashish']

In [25]:
a

[1, 2, 4, 4, 'ashish']

In [26]:
type(a)

list

In [22]:
np.array(a)

array(['1', '2', '4', '4', 'ashish'], dtype='<U11')

In [38]:
b=np.array([1,2,4,4,'ashish'])

In [39]:
b

array(['1', '2', '4', '4', 'ashish'], dtype='<U11')

In [40]:
type(b)

numpy.ndarray

In [41]:
b.ndim

1

In [42]:
b.shape

(5,)

In [43]:
b.size

5

In [94]:
c=np.array([[[[[1,2,4,4,'ashish']]]]])

In [95]:
c.ndim

5

In [96]:
type(c)

numpy.ndarray

In [47]:
c.shape  #RowsxCol

(1, 1, 1, 5)

In [48]:
c.size

5

# Basic Functions of numpy

In [57]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [63]:
b=np.array([1,2,4,4,5])
b

array([1, 2, 4, 4, 5])

In [64]:
np.add(a,b)

array([ 2,  4,  7,  8, 10])

In [66]:
np.subtract(a,b)

array([ 0,  0, -1,  0,  0])

In [67]:
np.subtract(b,a)

array([0, 0, 1, 0, 0])

In [69]:
np.multiply(a,b)

array([ 1,  4, 12, 16, 25])

In [70]:
np.divide(a,b)

array([1.  , 1.  , 0.75, 1.  , 1.  ])

In [71]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [72]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

## Zeroes, Ones, Eyes, Full

In [86]:
a=np.zeros((5,5))

In [87]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [88]:
type(a)

numpy.ndarray

In [89]:
a.ndim

2

In [92]:
a=np.zeros((4,5,5))

In [93]:
a

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [124]:
np.ones((7,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [101]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [106]:
a=np.full(shape=(5,5),fill_value=7)

In [107]:
a

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [108]:
type(a)

numpy.ndarray

In [109]:
a.ndim

2

In [110]:
a.dtype

dtype('int32')

In [111]:
b=np.full(shape=(5,5),fill_value=7.0)

In [112]:
b

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [113]:
type(b)

numpy.ndarray

In [114]:
b.ndim

2

In [115]:
b.dtype

dtype('float64')

In [116]:
import random
import math

In [148]:
np.random.rand(5,2)

array([[0.179712  , 0.65623868],
       [0.11910512, 0.28607718],
       [0.83187434, 0.70075111],
       [0.02152861, 0.49012632],
       [0.68742537, 0.30988863]])

In [143]:
np.random.randn(5,2)

array([[ 0.21623421,  0.01411394],
       [ 1.22365941, -2.07338441],
       [-0.18354081,  1.11864527],
       [-1.01162263,  0.83176196],
       [ 0.4114129 ,  0.45488231]])

In [130]:
np.random.randn(2,5,2)

array([[[-0.70087322,  1.76862597],
        [-0.41902382, -1.41742039],
        [ 0.58582607,  0.11745678],
        [-0.26637154, -0.2943611 ],
        [-0.37042729, -0.66104233]],

       [[ 0.52250856,  0.00530711],
        [-1.05584543,  0.57682467],
        [-0.41685467,  1.60421456],
        [-0.35928001, -0.12610313],
        [-1.9332739 , -1.2007328 ]]])

In [155]:
np.random.randint(1,100)

32

In [156]:
type(np.random.randint(1,100))

int

In [149]:
list1

[1, 2, 3]

In [152]:
np.random.choice(list1)

3

In [154]:
np.random.random_integers(1,100)

C:\Users\thero\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  """Entry point for launching an IPython kernel.


21

In [157]:
type(np.random.random_integers(1,100))

C:\Users\thero\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  """Entry point for launching an IPython kernel.


numpy.int32

In [164]:
np.random.random()

0.8585805314709642

## Reshape

In [174]:
a=np.random.randn(5,2)

In [175]:
a

array([[ 3.2389604 , -0.11883483],
       [-0.08438009, -0.52517857],
       [ 0.45935855,  0.60721652],
       [-1.28169093, -0.84820691],
       [-0.59506492,  1.22227111]])

In [176]:
a.size

10

In [179]:
a.reshape(2,5)

array([[ 3.2389604 , -0.11883483, -0.08438009, -0.52517857,  0.45935855],
       [ 0.60721652, -1.28169093, -0.84820691, -0.59506492,  1.22227111]])

In [181]:
a.reshape(1,10)

array([[ 3.2389604 , -0.11883483, -0.08438009, -0.52517857,  0.45935855,
         0.60721652, -1.28169093, -0.84820691, -0.59506492,  1.22227111]])

In [184]:
c=a.reshape(10,1)

In [185]:
c

array([[ 3.2389604 ],
       [-0.11883483],
       [-0.08438009],
       [-0.52517857],
       [ 0.45935855],
       [ 0.60721652],
       [-1.28169093],
       [-0.84820691],
       [-0.59506492],
       [ 1.22227111]])

In [186]:
b=c.copy()

In [189]:
b

array([[ 3.2389604 ],
       [-0.11883483],
       [-0.08438009],
       [-0.52517857],
       [ 0.45935855],
       [ 0.60721652],
       [-1.28169093],
       [-0.84820691],
       [-0.59506492],
       [ 1.22227111]])

# Indexing and Slicing

In [1]:
lst1=[1,2,3,4,5]

In [3]:
lst1[1]

2

In [17]:
a=np.array([[[[lst1]]]])

In [18]:
a

array([[[[[1, 2, 3, 4, 5]]]]])

In [19]:
a.ndim

5

In [26]:
a[0][0][0][0][1]

2

In [27]:
b=np.array(np.random.randn(4,5))

In [40]:
b

array([[ 1.18075557, -1.43915355,  0.04107663,  0.75416643,  0.32986946],
       [-1.41721063,  0.18964316,  0.34293192, -1.9637611 ,  0.50374697],
       [-0.59587273,  0.88172861, -1.0520292 ,  0.71357438,  0.32543548],
       [ 1.23829039,  0.79877609,  0.07158673,  0.0436136 , -0.87635787]])

In [44]:
b=np.array([[b]])

In [45]:
b.ndim

4

In [46]:
b

array([[[[ 1.18075557, -1.43915355,  0.04107663,  0.75416643,
           0.32986946],
         [-1.41721063,  0.18964316,  0.34293192, -1.9637611 ,
           0.50374697],
         [-0.59587273,  0.88172861, -1.0520292 ,  0.71357438,
           0.32543548],
         [ 1.23829039,  0.79877609,  0.07158673,  0.0436136 ,
          -0.87635787]]]])

In [50]:
b[0][0][0][1]

-1.4391535473137458

### Slicing

In [52]:
a=np.array([1,2,3,4,5,6,7,8])

In [53]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
a[0:3]

array([1, 2, 3])

In [59]:
b

array([[[[ 1.18075557, -1.43915355,  0.04107663,  0.75416643,
           0.32986946],
         [-1.41721063,  0.18964316,  0.34293192, -1.9637611 ,
           0.50374697],
         [-0.59587273,  0.88172861, -1.0520292 ,  0.71357438,
           0.32543548],
         [ 1.23829039,  0.79877609,  0.07158673,  0.0436136 ,
          -0.87635787]]]])

In [75]:
b[0][0][2][1:3]

array([ 0.88172861, -1.0520292 ])

# Copying

In [81]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
c=a.copy()

In [86]:
c

array([1, 2, 3, 4, 5, 6, 7, 8])

# Sorting

In [88]:
a=np.array([3,1,7,9,4,2,6,5,21,10])

In [89]:
a

array([ 3,  1,  7,  9,  4,  2,  6,  5, 21, 10])

In [90]:
a.sort()

In [91]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  9, 10, 21])

# Appending and Inserting

In [92]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  9, 10, 21])

In [93]:
b=[1,2,3,4,5]

In [94]:
b.append(100)

In [95]:
b

[1, 2, 3, 4, 5, 100]

In [99]:
a=np.append(a,100)

In [100]:
a

array([  1,   2,   3,   4,   5,   6,   7,   9,  10,  21, 100, 100])

In [102]:
a=np.insert(a,1,200)

In [103]:
a

array([  1, 200,   2,   3,   4,   5,   6,   7,   9,  10,  21, 100, 100])

In [104]:
b.insert(1,200)

In [105]:
b

[1, 200, 2, 3, 4, 5, 100]

In [106]:
a=np.insert(a,0,1000)

In [107]:
a

array([1000,    1,  200,    2,    3,    4,    5,    6,    7,    9,   10,
         21,  100,  100])

# Removing

In [117]:
# axis=0 means Rows, axis=1 Means Col

In [108]:
np.delete(a,0)

array([  1, 200,   2,   3,   4,   5,   6,   7,   9,  10,  21, 100, 100])

In [124]:
b=np.array(np.random.randn(4,5))

In [125]:
b

array([[-0.41025026, -1.11287097, -0.07623706,  1.80378305,  0.19153708],
       [ 0.43062938, -2.26261181,  0.41283438, -0.4182859 , -1.1882668 ],
       [-0.31856629, -0.80142032,  0.14821804, -1.53979066,  0.23767856],
       [-0.79138351, -0.51358535, -1.33154811, -0.59978404, -0.18783796]])

In [126]:
b=np.delete(b,0,axis=0)

In [127]:
b

array([[ 0.43062938, -2.26261181,  0.41283438, -0.4182859 , -1.1882668 ],
       [-0.31856629, -0.80142032,  0.14821804, -1.53979066,  0.23767856],
       [-0.79138351, -0.51358535, -1.33154811, -0.59978404, -0.18783796]])

In [128]:
b=np.delete(b,0,axis=1)

In [129]:
b

array([[-2.26261181,  0.41283438, -0.4182859 , -1.1882668 ],
       [-0.80142032,  0.14821804, -1.53979066,  0.23767856],
       [-0.51358535, -1.33154811, -0.59978404, -0.18783796]])

In [130]:
b=np.delete(b,1,axis=1)

In [131]:
b

array([[-2.26261181, -0.4182859 , -1.1882668 ],
       [-0.80142032, -1.53979066,  0.23767856],
       [-0.51358535, -0.59978404, -0.18783796]])

# Combining

In [132]:
a

array([1000,    1,  200,    2,    3,    4,    5,    6,    7,    9,   10,
         21,  100,  100])

In [142]:
a=np.array(np.random.randn(3,3))

In [143]:
a

array([[ 1.53341309,  1.68416388, -0.69709956],
       [-0.48603769,  1.60737689,  1.20171685],
       [ 0.06951832, -0.82714317,  0.41921651]])

In [133]:
b

array([[-2.26261181, -0.4182859 , -1.1882668 ],
       [-0.80142032, -1.53979066,  0.23767856],
       [-0.51358535, -0.59978404, -0.18783796]])

In [145]:
np.concatenate((b,a))

array([[-2.26261181, -0.4182859 , -1.1882668 ],
       [-0.80142032, -1.53979066,  0.23767856],
       [-0.51358535, -0.59978404, -0.18783796],
       [ 1.53341309,  1.68416388, -0.69709956],
       [-0.48603769,  1.60737689,  1.20171685],
       [ 0.06951832, -0.82714317,  0.41921651]])

In [147]:
np.concatenate((a,b),axis=1)

array([[ 1.53341309,  1.68416388, -0.69709956, -2.26261181, -0.4182859 ,
        -1.1882668 ],
       [-0.48603769,  1.60737689,  1.20171685, -0.80142032, -1.53979066,
         0.23767856],
       [ 0.06951832, -0.82714317,  0.41921651, -0.51358535, -0.59978404,
        -0.18783796]])

# Assiging

In [148]:
a=np.array([1,2,3,4,5])

In [149]:
a

array([1, 2, 3, 4, 5])

In [151]:
a[0]=7

In [152]:
a

array([7, 2, 3, 4, 5])

In [153]:
a[1]=9

In [154]:
a

array([7, 9, 3, 4, 5])